name: Releases to Telegram       # название скрипта, которое будет отображаться во вкладке Actions репозитория

on:                              # действие, по которому запускается скрипт
  schedule:                      # в данном случае, это выполнение по таймеру
    - cron: '0 0,8,16 * * *'     # запускает workflow в 00:00, 08:00 и 16:00 по UTC каждый день.
  workflow_dispatch:             # чтобы скрипт можно было запускать вручную

jobs:                            # выполняемые в рамках скрипта работы
  Releases_to_Telegram:          # имя джобы
    runs-on: ubuntu-latest       # запускаем на образе последней версии ubuntu
    env:                         # задаём переменные окружения для джобы
      CURRENT: current
      CURRENT_NAME: current_name
      CURRENT_NAME_IN_REPO: current_name_in_repo
      
    steps:
    - uses: actions/checkout@v3

    - name: Get latest release
      run: python scripts/get_release.py

    - name: Send to channel
      if: success() && env.CURRENT_NAME != env.CURRENT_NAME_IN_REPO
      env:                                                  # задаём переменные окружения
        TG_KEY: ${{ secrets.TG_KEY }}                       # TG_KEY берется из "секрета" репозитория с именем "TG_KEY" - это API-ключ для управления Telegram-ботом 
        TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}         # TG_CHANNEL_ID берется из "секрета" репозитория с именем "TG_CHANNEL_ID" - это id канала, куда будут публиковаться сообщения от бота
      run: |
          python scripts/send_to_channel.py
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add current.json
          git commit -m "Вышел релиз, поменялся current.json"
          git push
